### PR TITLE
Update prime-number.py

### PR DESCRIPTION
**Pull request by oniani**
Note that prime numbers could only be represented as `6*k + 1` or `6*k - 1` where `k` is an integer `(k > 0)`.
To see why it's true, let's look at all the representations of an integer (in terms of divisibility by 6).
The possible representations are: `6*k`, `6*k + 1`, `6*k + 2`, `6*k + 3`, `6*k + 4`, and `6*k + 5`.

`6*k` cannot be a prime since it's divisible by 6
`6*k + 2` cannot be a prime since it's divisible by 2
`6*k + 3` cannot be a prime since it's divisible by 3
`6*k + 4` cannot be a prime since it's divisible by 2

Finally, we are left with `6*k + 1` and `6*k + 5` which are indeed the only valid representations for a prime number.

P.S. Thought adding a bit of optimization wouldn't hurt.

### CODE REVIEW

**Comment by mre** [comment]
Nice explanation. Never heard about that, but it makes sense. Could you add a link above the if condition at line 6 for further reading? Just to help people understand how this works.

**Comment by oniani** [comment]
Done.
I also made some changes in the code to make sure we got all the cases.

**Comment by oniani** [comment]
Done.

I also made some additional changes in the code to handle the edge cases. Particularly, the cases when `n = 2` and `n = 3`. Since the minimal value of `6*k - 1` is `5` (when `k = 1`), the cases when `n = 2` and `n = 3` were left out. For this reason, I moved the `elif n == 2` statement above the new optimization statement and also included the case when `n = 3` so now it looks like this:
```python
elif n in [2, 3]:
    return True
Please take a look.

**Comment by oniani** [comment]
Done.

I also made some additional changes in the code to handle the edge cases. Particularly, the cases when `n = 2` and `n = 3`. Since the minimal value of `6*k - 1` is `5` (when `k = 1`), the cases when `n = 2` and `n = 3` were left out. For this reason, I moved the `elif n == 2` statement above the new optimization statement and also included the case when `n = 3` so now it looks like this:
```python
elif n in [2, 3]:
    return True
```

Also, the `elif` statement for checking whether `n` is even or not was redundant (`6*k + 1` and `6*k + 5` are always odd for integer `k`) so I got rid of it.

Please take a look.

**Comment by mre** [comment]
Good job! 🌈

**Pull request merged**
