### PR TITLE
Kotlin: can scramble

### PR DESCRIPTION
**Pull request by Fleshgrinder**

### CODE REVIEW

**Comment by mre** [comment]
😮

**Comment by poliak9** [comment]
This doesnt work - `"ac".canScramble("bb")` returns true

**Comment by mre** [comment]
Oh, that's a nice edge case that isn't covered. Would you like to attempt a fix @poliak9?

**Comment by poliak9** [comment]
I don't know Kotlin so idk what the idiomatic solution is

**Comment by Fleshgrinder** [comment]
In that case multiple solutions are incorrect. The easiest approach is to simply sort it like in many other solutions, one way to achieve that is with `toCharArray().sortedArray().contentEquals(other.toCharArray().sortedArray())` but it looses O(n) complexity. Not sure if an O(n) solution is actually possible but I'll try to figure one out. ☺️

**Comment by poliak9** [comment]
You are right some other solutions are incorrect as well.
I think there's O(n) time O(1) space solution actually

**Comment by mre** [comment]
One thing that could be done is converting the string into a `HashMap` which counts the occurrences of each character. 

E.g. for `abcaba` it would be

```python
count = {'a': 3, 'b': 2, 'c': 1 }
```

Checking if two strings can be scrambled would then mean checking that the maps for both strings are identical.

Building the `HashMap` would be O(n) average time (O(n^2) in the worst-case scenario when there are just identical characters in the string and the map insertion degrades to traversing a linked list).
The space would be constant as there are only a limited numeber of characters for a given encoding (e.g. 26 in the case of ASCII) and we store maximum one integer for each each (the count of occurrences).

@poliak9 was this what you had in mind?

Here's some Rust (as I don't know Kotlin either):

```rust
use std::collections::HashMap;

trait CharMap {
    fn char_map(self) -> HashMap<char, u32>;
}

impl<'a> CharMap for &'a str {
    fn char_map(self) -> HashMap<char, u32> {
        let mut map = HashMap::new();
        for c in self.chars() {
            map.entry(c).and_modify(|count| *count += 1).or_insert(1);
        }
        map
    }
}

pub fn can_scramble(input: &str, output: &str) -> bool {
    input.char_map() == output.char_map()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        assert_eq!(can_scramble("", ""), true);
        assert_eq!(can_scramble("abc", "cba"), true);
        assert_eq!(can_scramble("aaa", "aa"), false);
        assert_eq!(can_scramble("aab", "bba"), false);
        assert_eq!(can_scramble("ac", "bb"), false);
    }
}
```

@Fleshgrinder, your input would be appreciated on the Rust code.

**Comment by poliak9** [comment]
@mre No actually I had in mind your solution for [anagram detection](https://github.com/mre/the-coding-interview/tree/master/problems/anagram-detection) :D which is basically an extension of this problem. So you would have a [char-> prime] map and compute a hash. 

Also I don't really follow your O(n^2) argument - if you have the same characters you just increase the counter not traverse the collisions. so building the hashmap counter is O(n).

But you are right with the finite alphabet argument that the hashmap is actually O(1) space, I didn't realize that.

**Comment by mre** [comment]
> No actually I had in mind your solution for anagram detection :D which is basically an extension of this problem. So you would have a [char-> prime] map and compute a hash.

Ah alright; that should work as well. 

> Also I don't really follow your O(n^2) argument - if you have the same characters you just increase the counter not traverse the collisions. so building the hashmap counter is O(n).

True, my bad.

> But you are right with the finite alphabet argument that the hashmap is actually O(1) space, I didn't realize that.

So I'd say in the end it's kind of the same idea as the prime map: we are looking for *some* kind of unique, order-independent fingerprint for the strings so that we can compare them.
The uniqueness is the problem with the current solution, as "ac" and "bb" produce the same character sum.
I'm fine with either solution we discussed and I'd appreciate a PR but in terms of idiomatic Kotlin I cannot give much advice, though. ;)

**Comment by Fleshgrinder** [comment]
@poliak9 && @mre see #120 for Java and Kotlin.

**Comment by mre** [comment]
Also updated the Rust version now.

**Pull request merged**
