### PR TITLE
feat(codejam): add the 2019 qualification for java

### PR DESCRIPTION
**Pull request by yirrilo**
Hi there, 
Here is a solution for one af the codejam event.
Best regards

### CODE REVIEW

**Comment by TheMly** [comment]
Thanks! We should contribute to this repo a lot more with these kind of exercises from events :)

 Do you know where else can I find exercises of this genre from contests and such?

**Comment by mre** [comment]
Looks good @yirrilo. Merging. Thanks for your contribution.

**Comment by yirrilo** [comment]
@TheMly, I use to work on Google events like Code Jam, Hashcode and so forth. There is although a bunch of events relying to isograd.com like battledev or MeilleurDevDeFrance. Let's have a look !

**Comment by yirrilo** [comment]
@mre, thanks for merging.

**Comment by TheMly** [comment]
@yirrilo That's nice! I see there are a lot of these exercises in the archive of those events. Will take a look sure. thanks! ;)

**Pull request merged**
